# Generated by Django 3.2.6 on 2021-08-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_store_table'),
        ('medicine', '0002_auto_20210817_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('order_fulfilment_datetime', models.DateTimeField(null=True)),
                ('order_fulfilment_status', models.TextField(default='pending')),
                ('total_amount', models.FloatField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.medicine')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'order_medicine',
                'unique_together': {('order_id', 'medicine_id')},
            },
        ),
    ]
