# Generated by Django 3.2.6 on 2021-08-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='ordermedicine',
            table='order_medicine',
        ),
    ]
